name: Reframed Media TEST
favicon: null
layout_spectrum: 0.27572377934120595
typography_spectrum: 0.14326064148917794
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.675211827037856
  lightness: 0.995410768315196
  saturation: 0.2622695416212082
  rhythmicContrast: 0.7019239321816713
purpose: []
